# Generated by Django 2.0.1 on 2018-01-19 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('opened_on', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('serving', models.BooleanField(default=True)),
                ('is_mod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255, verbose_name='Server Name')),
                ('state', models.CharField(default='not_working', max_length=11)),
                ('employed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField()),
                ('state', models.CharField(max_length=8, verbose_name='Table State')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_server', to='serving.Server')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_table', to='serving.Table'),
        ),
        migrations.AddField(
            model_name='moditem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.OrderItem'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='serving.OrderItem'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_item_seat', to='serving.Seat'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serving.Server'),
        ),
        migrations.AddField(
            model_name='bill',
            name='last_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_server', to='serving.Server'),
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_table', to='serving.Table'),
        ),
    ]
